spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health_project
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: "Health Project"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          writeTimeout: 10_000
          connectionTimeout: 10_000
          timeout: 10_000
          auth: true
          starttls:
            enable: true
            required: true

auth:
  jwt:
    user:
      access-token:
        encryption-key: "38f05b12bc0ca4fb5a61514ebf37069b3905b99dd999f6ca1814dabc5bd1bbc9"
        duration: 15
        unit: minutes
      refresh-token:
        encryption-key: "3d8d415f6e71533c37b830c6f93e5de1d8a3275b18e33f52633be458e7a2e050"
        duration: 8
        unit: days

  session:
    duration: 7
    unit: days
  allowed-uris:
    - "/swagger-ui/index.html"
    - "/v3/api-docs"
    - "/v3/api-docs/swagger-config"
  cors:
    allowed-uris:
      - "http://localhost:3000"

